- hosts: all 
  name: Configure k8s firewall control planes
  become: yes
  tasks:
    - fail:
       msg: "OS should be Rocky, not {{ ansible_distribution }} {{ ansible_distribution_version }}"
      when: ansible_distribution != 'Rocky' or ansible_distribution_version != '8.10'

    - name: Cleaning networking kubernetes
      shell: |
        sudo rm -rf /etc/sysctl.d/k8s.conf

    - name: create k8s repo file
      file:
        path: "/etc/sysctl.d/k8s.conf"
        state: "touch"
        owner: root
        group: root

    - name: Config file for networking kubernetes
      blockinfile:
        path: /etc/sysctl.d/k8s.conf
        block: |
          net.ipv4.ip_forward = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1

    - name: Apply changes
      shell: |
        sudo sysctl --system
