- hosts: nodes
  name: Configure k8s swap off on nodes
  become: yes
  tasks:
    - fail:
       msg: "OS should be Rocky, not {{ ansible_distribution }} {{ ansible_distribution_version }}"
      when: ansible_distribution != 'Rocky' or ansible_distribution_version != '9.5'

    - name: Turn off swap
      shell: |
        sudo swapoff -a

    - name: Make the changes persist across reboots by typing.
      lineinfile:
        path: /etc/fstab
        regexp: '^(.*)\/dev\/mapper\/rl-swap(.*)$'
        line: '#/dev/mapper/rl-swap     none                    swap    defaults        0 0'
        backrefs: yes

